### ISSUE TITLE
Some character in password does lead to error

### ISSUE THREAD

**Issue by theBest3000** [DannyGB/KeePassTouch#36] opened 2018-10-20 10:00 UTC
Databases containing at least the character "€" can't be open by the application. See included testdatabase. The password is "ubports€a". 
[testdatabase.zip](https://github.com/DannyGB/KeePassTouch/files/2498014/testdatabase.zip)

Not sure about other characters.

**Comment by DannyGB** [comment] 2019-07-13 20:35
Duplicate of #18, I'm going to move the test DB you supplied over to that issue

**Closed by DannyGB** 2019-07-13 20:35 UTC
Labels: bug, replicated
